### ISSUE TITLE
Restructure Documentation

### ISSUE THREAD

**Issue by gked** [pocketnetteam/documentation#21]
Update current documentation structure to the one proposed below:

- [ ] Getting Started
	- [x] Platform overview
	- [x] Quick start guide
	- [x] How to leave feedback on Bastyon
	- [x] FAQs
2. Community and Support
	- Community guidelines
	- Support channels
	- Feature requests and bug reporting
3. Contribution Guide
	- How to contribute to Bastyon
	- Code of conduct
	- Development workflow
4. User Guide
	- Account setup and management
	- Using the social platform features
	- Messenger functionality
	- Authorship on Bastyon
	- Tutorials and How Tos
	- Troubleshooting
5. Architecture and Design
	- System architecture
	- Decentralization and blockchain integration
	- Security features
6. Developer Documentation
	- API reference
	- SDK documentation
	- MiniApps development guide
	- Best practices and examples
	- Tutorials
### Documentation Roadmap
Documentation is not the goal in itself but rather a perpetual process of refinement  of what is being communicated to project participants or users. Nevertheless, there is a sequence of the execution that we can follow to build robust processes. 

- [ ] Assessment and Planning
	- [ ] Audit existing documentation
	- [ ] Identify key stakeholders and their needs
		- [ ] Create documentation channel and invite the stakeholders
	- [ ] Communicate to key stakeholders the expectations and the proposed changes
	- [ ] Get an agreement from stakeholders
	- [ ] Define documentation goals and metrics
- [ ] Infrastructure Setup
	- [ ] Choose a new documentation platform (e.g., GitBook, ReadTheDocs, MediaWiki, etc ) that supports user feedback, or use the existing one.
	- [ ] Choose other tooling (We need something for translation, dead links scanner, etc)
	- [ ] Set up version control integration with feedback.
	- [ ] Establish a contribution workflow
	- [ ] Implement, "you make the change, you document the update" principle for developer community.
- [ ] Content Creation
	- [ ] Develop a style guide
	- [ ] Create templates for different document types
	- [ ] Begin writing/updating core documentation sections
- [ ] Review and Iteration
	- [ ] Implement peer review process
	- [ ] Gather user feedback
	- [ ] Continuously improve and update content
- [ ] Launch and Promotion
	- [ ] Promote documentation through various channels
- [ ] Maintenance and Expansion
	- [ ] Regular content audits and updates. Can we use some sort of tooling to identify dead links, etc?
	- [ ] Expand documentation based on user needs and platform growth
	- [ ] Create online groups for discussions related to documentation
	- [ ] Train community contributors

**Comment by andyoknen** [comment]
It looks amazing! I would reverse paragraphs 3 and 4
