### ISSUE TITLE
Contribution.md?

### ISSUE THREAD

**Issue by gked** [pocketnetteam/documentation#5]
Hi PocketNet team. Do you have any guidelines on how to contribute with bringing general Product direction proposals, new feature proposals and making code changes documented some place?

**Comment by andyoknen** [comment]
Hello @gked! Unfortunately there is no such document(:
But we are always happy to help in any form;)

**Comment by gked** [comment]
@andyoknen Understood, thanks.
I have  a few suggestions around Bastyon features and a potential bug to report (Android platform). I guess, I can create separate issues here and you can triage whether this is the appropriate place or I should move my questions/proposals elsewhere.
