### ISSUE TITLE
A link to the documentation page seems to be broken

### ISSUE THREAD

**Issue by gked** [pocketnetteam/documentation#7]
I remember that I was able to navigate to the deployed documentation [page](https://pocketnet.app/documentation) before. 
It seems that I lost the ability though and get a 404 error. Has the deployment location been changed?

![image](https://user-images.githubusercontent.com/12704474/209618001-4d234c0a-968b-488a-a2d8-5e53605bd769.png)

**Comment by andyoknen** [comment]
As far as I know, we are abandoning the https://pocketnet.app domain
It would be more correct to use https://bastyon.com/documentation

But it doesn't work either.. I will discuss with my colleagues where these links should lead, but I think that the most logical place is https://docs.bastyon.com

**Comment by gked** [comment]
Thank you! https://docs.bastyon.com/ seems like the right place to be navigated to. I will create a PR with a change to the README.md file in a few.
